// voxes
#include "vox.c"
#include "vox_generated.c"
#include "vox_file.c"
#include "block.c"
#include "blocks_solids.c"
#include "block_meta.c"
#include "block_instanced.c"
// models
#include "node.c"
#include "process.c"
#include "model_lods.c"
#include "models.c"
#include "node_colors.c"
// TODO: Refactor to model_lods + blueprint for grass
#include "grass.c"
#include "generated.c"
#include "slime.c"
#include "cookie.c"
