zox_hashmap(byte3_hashmap, entity, 0, byte3, uint, get_byte3_hash)
zox_hashmap(int3_hashmap, entity, 0, int3, uint, get_int3_hash)
zox_hashmap(string_hashmap, entity, 0, string_data, uint, get_string_hash)
zox_hashmap(int_hashmap, entity, 0, int, uint,  get_int_hash)
zox_hashmap(int2_hashmap, entity, 0, int2, uint, get_int2_hash)
