// Main
#include "start.c"
#include "realm.c"
#include "realm_new.c"
#include "realm_pick.c"
#include "settings.c"
#include "main.c"
// Game
#include "taskbar.c"
#include "touch.c"
#include "pause.c"
#include "respawn.c"
// Editor
#include "terminal.c"
