
#define ZOX_SDL_SCANCODE_SPACE SDL_SCANCODE_SPACE
#define ZOX_SDL_KEYCODE_SPACE SDLK_SPACE

#define ZOX_SDL_SCANCODE_BACK_QUOTE SDL_SCANCODE_GRAVE
#define ZOX_SDL_KEYCODE_BACK_QUOTE SDLK_GRAVE

#define ZOX_SDL_SCANCODE_ENTER SDL_SCANCODE_RETURN
#define ZOX_SDL_KEYCODE_ENTER SDLK_RETURN

#define ZOX_SDL_SCANCODE_ESCAPE SDL_SCANCODE_ESCAPE
#define ZOX_SDL_KEYCODE_ESCAPE SDLK_ESCAPE

#define ZOX_SDL_SCANCODE_BACKSPACE SDL_SCANCODE_BACKSPACE
#define ZOX_SDL_KEYCODE_BACKSPACE SDLK_BACKSPACE

#define ZOX_SDL_SCANCODE_TAB SDL_SCANCODE_TAB
#define ZOX_SDL_KEYCODE_TAB SDLK_TAB

#define ZOX_SDL_SCANCODE_LEFT_CONTROL SDL_SCANCODE_LCTRL
#define ZOX_SDL_KEYCODE_LEFT_CONTROL SDLK_LCTRL

#define ZOX_SDL_SCANCODE_RIGHT_CONTROL SDL_SCANCODE_RCTRL
#define ZOX_SDL_KEYCODE_RIGHT_CONTROL SDLK_RCTRL

#define ZOX_SDL_SCANCODE_LEFT_ALT SDL_SCANCODE_LALT
#define ZOX_SDL_KEYCODE_LEFT_ALT SDLK_LALT

#define ZOX_SDL_SCANCODE_RIGHT_ALT SDL_SCANCODE_RALT
#define ZOX_SDL_KEYCODE_RIGHT_ALT SDLK_RALT

#define ZOX_SDL_SCANCODE_LEFT_SHIFT SDL_SCANCODE_LSHIFT
#define ZOX_SDL_KEYCODE_LEFT_SHIFT SDLK_LSHIFT

#define ZOX_SDL_SCANCODE_RIGHT_SHIFT SDL_SCANCODE_RSHIFT
#define ZOX_SDL_KEYCODE_RIGHT_SHIFT SDLK_RSHIFT

#define ZOX_SDL_SCANCODE_UP SDL_SCANCODE_UP
#define ZOX_SDL_KEYCODE_UP SDLK_UP

#define ZOX_SDL_SCANCODE_DOWN SDL_SCANCODE_DOWN
#define ZOX_SDL_KEYCODE_DOWN SDLK_DOWN

#define ZOX_SDL_SCANCODE_LEFT SDL_SCANCODE_LEFT
#define ZOX_SDL_KEYCODE_LEFT SDLK_LEFT

#define ZOX_SDL_SCANCODE_RIGHT SDL_SCANCODE_RIGHT
#define ZOX_SDL_KEYCODE_RIGHT SDLK_RIGHT

#define ZOX_SDL_SCANCODE_A SDL_SCANCODE_A
#define ZOX_SDL_KEYCODE_A SDLK_A

#define ZOX_SDL_SCANCODE_B SDL_SCANCODE_B
#define ZOX_SDL_KEYCODE_B SDLK_B

#define ZOX_SDL_SCANCODE_C SDL_SCANCODE_C
#define ZOX_SDL_KEYCODE_C SDLK_C

#define ZOX_SDL_SCANCODE_D SDL_SCANCODE_D
#define ZOX_SDL_KEYCODE_D SDLK_D

#define ZOX_SDL_SCANCODE_E SDL_SCANCODE_E
#define ZOX_SDL_KEYCODE_E SDLK_E

#define ZOX_SDL_SCANCODE_F SDL_SCANCODE_F
#define ZOX_SDL_KEYCODE_F SDLK_F

#define ZOX_SDL_SCANCODE_G SDL_SCANCODE_G
#define ZOX_SDL_KEYCODE_G SDLK_G

#define ZOX_SDL_SCANCODE_H SDL_SCANCODE_H
#define ZOX_SDL_KEYCODE_H SDLK_H

#define ZOX_SDL_SCANCODE_I SDL_SCANCODE_I
#define ZOX_SDL_KEYCODE_I SDLK_I

#define ZOX_SDL_SCANCODE_J SDL_SCANCODE_J
#define ZOX_SDL_KEYCODE_J SDLK_J

#define ZOX_SDL_SCANCODE_K SDL_SCANCODE_K
#define ZOX_SDL_KEYCODE_K SDLK_K

#define ZOX_SDL_SCANCODE_L SDL_SCANCODE_L
#define ZOX_SDL_KEYCODE_L SDLK_L

#define ZOX_SDL_SCANCODE_M SDL_SCANCODE_M
#define ZOX_SDL_KEYCODE_M SDLK_M

#define ZOX_SDL_SCANCODE_N SDL_SCANCODE_N
#define ZOX_SDL_KEYCODE_N SDLK_N

#define ZOX_SDL_SCANCODE_O SDL_SCANCODE_O
#define ZOX_SDL_KEYCODE_O SDLK_O

#define ZOX_SDL_SCANCODE_P SDL_SCANCODE_P
#define ZOX_SDL_KEYCODE_P SDLK_P

#define ZOX_SDL_SCANCODE_Q SDL_SCANCODE_Q
#define ZOX_SDL_KEYCODE_Q SDLK_Q

#define ZOX_SDL_SCANCODE_R SDL_SCANCODE_R
#define ZOX_SDL_KEYCODE_R SDLK_R

#define ZOX_SDL_SCANCODE_S SDL_SCANCODE_S
#define ZOX_SDL_KEYCODE_S SDLK_S

#define ZOX_SDL_SCANCODE_T SDL_SCANCODE_T
#define ZOX_SDL_KEYCODE_T SDLK_T

#define ZOX_SDL_SCANCODE_U SDL_SCANCODE_U
#define ZOX_SDL_KEYCODE_U SDLK_U

#define ZOX_SDL_SCANCODE_V SDL_SCANCODE_V
#define ZOX_SDL_KEYCODE_V SDLK_V

#define ZOX_SDL_SCANCODE_W SDL_SCANCODE_W
#define ZOX_SDL_KEYCODE_W SDLK_W

#define ZOX_SDL_SCANCODE_X SDL_SCANCODE_X
#define ZOX_SDL_KEYCODE_X SDLK_X

#define ZOX_SDL_SCANCODE_Y SDL_SCANCODE_Y
#define ZOX_SDL_KEYCODE_Y SDLK_Y

#define ZOX_SDL_SCANCODE_Z SDL_SCANCODE_Z
#define ZOX_SDL_KEYCODE_Z SDLK_Z

#define ZOX_SDL_SCANCODE_F1 SDL_SCANCODE_F1
#define ZOX_SDL_KEYCODE_F1 SDLK_F1

#define ZOX_SDL_SCANCODE_F2 SDL_SCANCODE_F2
#define ZOX_SDL_KEYCODE_F2 SDLK_F2

#define ZOX_SDL_SCANCODE_F3 SDL_SCANCODE_F3
#define ZOX_SDL_KEYCODE_F3 SDLK_F3

#define ZOX_SDL_SCANCODE_F4 SDL_SCANCODE_F4
#define ZOX_SDL_KEYCODE_F4 SDLK_F4

#define ZOX_SDL_SCANCODE_F5 SDL_SCANCODE_F5
#define ZOX_SDL_KEYCODE_F5 SDLK_F5

#define ZOX_SDL_SCANCODE_F6 SDL_SCANCODE_F6
#define ZOX_SDL_KEYCODE_F6 SDLK_F6

#define ZOX_SDL_SCANCODE_F7 SDL_SCANCODE_F7
#define ZOX_SDL_KEYCODE_F7 SDLK_F7

#define ZOX_SDL_SCANCODE_F8 SDL_SCANCODE_F8
#define ZOX_SDL_KEYCODE_F8 SDLK_F8

#define ZOX_SDL_SCANCODE_F9 SDL_SCANCODE_F9
#define ZOX_SDL_KEYCODE_F9 SDLK_F9

#define ZOX_SDL_SCANCODE_F10 SDL_SCANCODE_F10
#define ZOX_SDL_KEYCODE_F10 SDLK_F10

#define ZOX_SDL_SCANCODE_F11 SDL_SCANCODE_F11
#define ZOX_SDL_KEYCODE_F11 SDLK_F11

#define ZOX_SDL_SCANCODE_F12 SDL_SCANCODE_F12
#define ZOX_SDL_KEYCODE_F12 SDLK_F12

#define ZOX_SDL_SCANCODE_0 SDL_SCANCODE_0
#define ZOX_SDL_KEYCODE_0 SDLK_0

#define ZOX_SDL_SCANCODE_1 SDL_SCANCODE_1
#define ZOX_SDL_KEYCODE_1 SDLK_1

#define ZOX_SDL_SCANCODE_2 SDL_SCANCODE_2
#define ZOX_SDL_KEYCODE_2 SDLK_2

#define ZOX_SDL_SCANCODE_3 SDL_SCANCODE_3
#define ZOX_SDL_KEYCODE_3 SDLK_3

#define ZOX_SDL_SCANCODE_4 SDL_SCANCODE_4
#define ZOX_SDL_KEYCODE_4 SDLK_4

#define ZOX_SDL_SCANCODE_5 SDL_SCANCODE_5
#define ZOX_SDL_KEYCODE_5 SDLK_5

#define ZOX_SDL_SCANCODE_6 SDL_SCANCODE_6
#define ZOX_SDL_KEYCODE_6 SDLK_6

#define ZOX_SDL_SCANCODE_7 SDL_SCANCODE_7
#define ZOX_SDL_KEYCODE_7 SDLK_7

#define ZOX_SDL_SCANCODE_8 SDL_SCANCODE_8
#define ZOX_SDL_KEYCODE_8 SDLK_8

#define ZOX_SDL_SCANCODE_9 SDL_SCANCODE_9
#define ZOX_SDL_KEYCODE_9 SDLK_9

// Events
#define ZOX_CONTROLLERDEVICEADDED SDL_EVENT_GAMEPAD_ADDED
#define ZOX_CONTROLLERDEVICEREMOVED SDL_EVENT_GAMEPAD_REMOVED
#define ZOX_CONTROLLERDEVICEREMAPPED SDL_EVENT_GAMEPAD_REMAPPED
#define ZOX_MOUSEWHEEL SDL_EVENT_MOUSE_WHEEL
#define ZOX_KEYDOWN SDL_EVENT_KEY_DOWN
#define ZOX_KEYUP SDL_EVENT_KEY_UP
#define ZOX_MOUSEBUTTONDOWN SDL_EVENT_MOUSE_BUTTON_DOWN
#define ZOX_MOUSEBUTTONUP SDL_EVENT_MOUSE_BUTTON_UP

#define ZOX_GAMEPAD_AXIS_LEFTX SDL_GAMEPAD_AXIS_LEFTX
#define ZOX_GAMEPAD_AXIS_LEFTY SDL_GAMEPAD_AXIS_LEFTY
#define ZOX_GAMEPAD_AXIS_RIGHTX SDL_GAMEPAD_AXIS_RIGHTX
#define ZOX_GAMEPAD_AXIS_RIGHTY SDL_GAMEPAD_AXIS_RIGHTY
#define ZOX_GAMEPAD_AXIS_LEFT_TRIGGER SDL_GAMEPAD_AXIS_LEFT_TRIGGER
#define ZOX_GAMEPAD_AXIS_RIGHT_TRIGGER SDL_GAMEPAD_AXIS_RIGHT_TRIGGER