#define vox_type_none 0
#define vox_type_soil 1
#define vox_type_blended 2
#define vox_type_rubble 3
#define vox_type_noisey 4
#define vox_type_bricks 5
#define vox_type_wood 6
#define vox_type_flowers 7
#define vox_type_road 8
#define vox_type_sand 9
